version: '3.8'

services:
  app:
    build: .
    container_name: dndn_be_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      JPA_HIBERNATE_DDL_AUTO: ${JPA_HIBERNATE_DDL_AUTO}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL}
      JPA_FORMAT_SQL: ${JPA_FORMAT_SQL}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      BUCKET_NAME: ${BUCKET_NAME}
      DNDN_IMAGE_FOLDER: ${DNDN_IMAGE_FOLDER}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

      JWT_HEADER: ${JWT_HEADER}
      JWT_PREFIX: ${JWT_PREFIX}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXP: ${JWT_ACCESS_EXP}
      JWT_REFRESH_EXP: ${JWT_REFRESH_EXP}

    networks:
      - dndn_network

  db:
    image: mysql:8.0
    container_name: dndn_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dndn_network

  redis:
    image: redis:7.0
    container_name: dndn_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dndn_network

volumes:
  db_data:

networks:
  dndn_network:
